print("Hello World !")
print("I am Ishita")
print("I am From Varanasi, India")
print("I am a 2nd Year Student at MNNIT.")
print("Email : 123ishitavandanajitendra@gmail.com")
print("Github : https://github.com/Ishh1505")
