print("Hello World !")
print("I am Aman Kanojiya")
print("I am From India")
print("I am 2nd Year Student at IIT Dhanbad.")
print("Email : aman.kanojiya4203@gmail.com")
print("Github : https://github.com/AMANKANOJIYA")